import Head from "next/head";
import styled from "styled-components";
import { Button } from "@taikai/rocket-kit";
import { useWeb3 } from "../hooks/useWeb3";
import { Container, Main, NavBar, BrandName, Menu , Footer, Title, SubTitle, Content}  from "../styles/home";
import ConnectModal from "../components/connect-wallet-modal";
import React, { useState } from 'react';
import useAddress from "../hooks/useAddress";

const AddressOpen = styled.div `
    button {
      border: 1px solid #ccc;
      text-transform: none;
    }
`;

type ActionType = () => void;

interface OnActionClick {
  onClick: ActionType;
}

export default function Home() {
  const { connected, disconnect, error } = useWeb3();
  const [isConnectModal, setConnectModal] = useState(false);

  const ShowEthAddress = (props: OnActionClick)=> {
    const { address = "" } = useAddress();
    const { onClick } = props;
    return (
      <AddressOpen>
        <Button 
          action={()=> onClick()}
          color="grey100"
          txtColor="black"
          value={address && `${address.slice(0, 6)}...${address.slice(-4)}`} 
          />      
    </AddressOpen>
    );
  }

  return (
    <Container>
      <Head>
        <title>Web3 BoilerPlate by Lay3rX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <BrandName> Web3 Boilerplate </BrandName>
        <Menu>
          {!connected && (
            <Button
              ariaLabel="Connect"
              className="button"
              color="green"
              value="Connect"
              variant="solid"
              action={()=> setConnectModal(true)}
            />
          )}
          { connected && <ShowEthAddress onClick={()=> setConnectModal(true)}/>}
        </Menu>
      </NavBar>
      {isConnectModal && <ConnectModal onClose={()=> setConnectModal(false)}/>}
      <Main>
        <Content>
          <Title>Lay3rX Web3 Boilerplate</Title>
          <SubTitle>Your web3 React.js template built with <strong>Dappkit</strong> +  <strong>RocketKit</strong></SubTitle>
        </Content>        
      </Main>
      <Footer>Made with ❤️ by LayerX - 2023</Footer>
    </Container>
  );
}
